### ISSUE TITLE
[BUG] Exception ticking world

### ISSUE THREAD

**Issue by BlackBaroness** [Trivernis/spigot-chunkmaster#115]
```[18:12:15] [Server thread/INFO]: [Chunkmaster] Task #1 running for 'world'. State: GENERATING. Progress: 3026779 chunks (21.52%) , ETA: 0h 1min 46s, Speed: 103225.5 ch/s, Last Chunk: 886, -33
[18:12:45] [Server thread/INFO]: [Chunkmaster] Task #1 running for 'world'. State: GENERATING. Progress: 3038598 chunks (21.61%) , ETA: 7h 51min 0s, Speed: 390.1 ch/s, Last Chunk: -307, 887
[18:13:16] [Server thread/INFO]: [Chunkmaster] Task #1 running for 'world'. State: GENERATING. Progress: 3050549 chunks (21.69%) , ETA: 7h 45min 44s, Speed: 394.1 ch/s, Last Chunk: -857, -572
[18:13:46] [Server thread/INFO]: [Chunkmaster] Task #1 running for 'world'. State: GENERATING. Progress: 3062500 chunks (21.78%) , ETA: 7h 43min 3s, Speed: 395.9 ch/s, Last Chunk: 891, -859
[18:14:16] [Server thread/INFO]: [Chunkmaster] Task #1 running for 'world'. State: GENERATING. Progress: 3074453 chunks (21.86%) , ETA: 7h 43min 38s, Speed: 395.0 ch/s, Last Chunk: 583, 892
[18:14:46] [Server thread/INFO]: [Chunkmaster] Task #1 running for 'world'. State: GENERATING. Progress: 3086237 chunks (21.95%) , ETA: 7h 49min 29s, Speed: 389.6 ch/s, Last Chunk: -862, 81
[18:14:46] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:916) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_12_R1.BiomeCache.a(SourceFile:69) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.WorldChunkManager.b(SourceFile:189) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:286) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:905) ~[patched_1.12.2.jar:git-Paper-1618]
	... 4 more
[18:14:46] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at net.minecraft.server.v1_12_R1.BiomeCache.a(SourceFile:69) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.WorldChunkManager.b(SourceFile:189) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:286) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:905) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

Paper 1.12.2, last build.

**Comment by Trivernis** [comment]
I don't think that bug is related to the plugin because it occurred when ticking the world which happens only to loaded (already generated chunks). It's probably a paper or minecraft vanilla bug.

**Comment by BlackBaroness** [comment]
Ok then
