### ISSUE TITLE
Paper async save problem

### ISSUE THREAD

**Issue by Daejangnamu** [Trivernis/spigot-chunkmaster#3]
[latest.zip](https://github.com/Trivernis/spigot-chunkmaster/files/3628626/latest.zip)

log check it please

**1.** `[07:06:10] [Server thread/FATAL]: Failed to prepare async save, attempting synchronous save
java.lang.ArrayIndexOutOfBoundsException: 163
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:348) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.LightEngineStorage.h(SourceFile:77) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.LightEngineLayer.a(SourceFile:215) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.ChunkRegionLoader.getAsyncSaveData(ChunkRegionLoader.java:310) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.asyncSave(PlayerChunkMap.java:490) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$11(PlayerChunkMap.java:522) ~[patched_1.14.4.jar:git-Paper-192]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_221]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.b(PlayerChunkMap.java:442) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.unloadChunks(PlayerChunkMap.java:405) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:533) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:348) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1208) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-192]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-192]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**2.**`[07:34:04] [Server thread/FATAL]: Failed to prepare async save, attempting synchronous save
java.lang.ArrayIndexOutOfBoundsException: null`

**Comment by Trivernis** [comment]
So I found some similar looking issues for [WorldBorder](https://www.spigotmc.org/threads/worldborder.339635/page-8) and think that this problem might be caused because of still pending chunks while the world is being saved. 

There is also an [issue](https://github.com/PaperMC/Paper/issues/2104) for papermc regarding the saving of single chunks.

**Comment by Trivernis** [comment]
[Forum entry on papermc forum.](https://papermc.io/forums/t/problem-with-async-saves/1787)

**Comment by Trivernis** [comment]
> Vanilla issue, paper will attempt the save again and it should be fine, just mojang and concurrency… Paper also saves chunks incrementally, the event is only fired on a full save, otherwise plugins using the save event to save their own stuff end up killing the server performance

[Answer](https://papermc.io/forums/t/problem-with-async-saves/1787/2?u=trivernis)

Therefore I'm removing the chunk unloading on save-event again.
