### ISSUE TITLE
Error while generating chunks

### ISSUE THREAD

**Issue by pdugery** [Trivernis/spigot-chunkmaster#44]
I'm running Paper-284 and am receiving errors when trying to generate chunks. The exact command I am trying to use is /chm generate world 11000000. I receive errors practically instantly after starting the task.

``>.... [20:52:57 FATAL]: Failed to read chunk data for task: Task for world: 'world' at 75,102 poi: false, hash: 1793445440
net.minecraft.server.v1_15_R1.ReportedException: Loading NBT data
at net.minecraft.server.v1_15_R1.NBTTagCompound.b(NBTTagCompound.java:451) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound.access$200(NBTTagCompound.java:23) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound$1.b(NBTTagCompound.java:42) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound$1.b(NBTTagCompound.java:27) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound.b(NBTTagCompound.java:444) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound.access$200(NBTTagCompound.java:23) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound$1.b(NBTTagCompound.java:42) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound$1.b(NBTTagCompound.java:27) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:117) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:86) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:76) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.RegionFileCache.read(RegionFileCache.java:159) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.read(PlayerChunkMap.java:1491) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.WorldServer$2.readData(WorldServer.java:148) ~[patched_1.15.2.jar:git-Paper-301]
at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:557) ~[patched_1.15.2.jar:git-Paper-301]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.15.2.jar:git-Paper-301]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.15.2.jar:git-Paper-301]
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) ~[?:1.8.0_242]
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_242]
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_242]
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_242]
at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_242]
at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[?:1.8.0_242]
at java.io.DataInputStream.readUTF(DataInputStream.java:609) ~[?:1.8.0_242]
at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_242]
at net.minecraft.server.v1_15_R1.NBTTagCompound.d(NBTTagCompound.java:439) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound.access$100(NBTTagCompound.java:23) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound$1.b(NBTTagCompound.java:39) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound$1.b(NBTTagCompound.java:27) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagList$1.b(NBTTagList.java:36) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagList$1.b(NBTTagList.java:18) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.NBTTagCompound.b(NBTTagCompound.java:444) ~[patched_1.15.2.jar:git-Paper-301]
... 16 more
>.... [20:52:57 WARN]: [Chunkmaster] Task #204761 for Chunkmaster v0.15-beta generated an exception
java.lang.RuntimeException: java.io.IOException: See logs for further detail
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.isChunkGenerated(CraftWorld.java:436) ~[patched_1.15.2.jar:git-Paper-301]
at net.trivernis.chunkmaster.lib.generation.GenerationTaskPaper.run(GenerationTaskPaper.kt:43) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-301]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-301]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.io.IOException: See logs for further detail
at net.minecraft.server.v1_15_R1.PlayerChunkMap.read(PlayerChunkMap.java:1487) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.readChunkData(PlayerChunkMap.java:1515) ~[patched_1.15.2.jar:git-Paper-301]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.getChunkStatusOnDisk(PlayerChunkMap.java:1572) ~[patched_1.15.2.jar:git-Paper-301]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.isChunkGenerated(CraftWorld.java:433) ~[patched_1.15.2.jar:git-Paper-301]
... 8 more``

**Comment by Trivernis** [comment]
The first one is a bug in the vanilla world generation so maybe report that to mojang.
Also can you provide the server log file?

**Comment by pdugery** [comment]
I was able to fix it. It turned out I had a decent amount of corrupted
chunks, which I assume came from switching hosts and not all the world's
files transferring. I ran region-fixer and it is now working fine. The only
issue I am having is that players are getting stuck on the loading terrain
screen while I am generating chunks. I originally thought it was just
because they were logging into an area with lots of entities and their
computers weren't great, but someone with pretty decent hardware (more than
enough ram and an i7) faced the same error. I'm still getting 20 tps, have
about 6 GB of free memory, and 90% cpu usage while generating chunks.

**Comment by Trivernis** [comment]
> The only
issue I am having is that players are getting stuck on the loading terrain
screen while I am generating chunks

Thats weird. The only solution I can think of is to decrease the generation speed, but if you say you've got 20 tps that shouldn't be an issue.
