### ISSUE TITLE
[BUG] Dynmap version is null when initializing dynmap support

### ISSUE THREAD

**Issue by wholenewmess** [Trivernis/spigot-chunkmaster#69]
**Describe the bug**
The plugin won't start up on the latest version of Spigot-1.16.1.

```
10.07 20:30:59 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'chm' in plugin Chunkmaster v1.0.1 - plugin is disabled.
10.07 20:30:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-87]
10.07 20:30:59 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

 - Java Version 8
 - Minecraft Server Version Paper 1.16.1 #87
 - Plugin Version 1.0.1

**Comment by Trivernis** [comment]
Please provide the full log file and the version (is it paper or spigot, you kinda mention both). The lines of the log you are showing don't provide any information about what happend and are probably unrelated to the plugin not starting.

**Comment by wholenewmess** [comment]
I'm using Paper 1.16.1 #86 now. Here's the full log file:
```
11.07 17:58:54 [Server] ERROR Error occurred while enabling Chunkmaster v1.2.1 (Is it up to date?)
11.07 17:58:54 [Server] INFO java.lang.IllegalStateException: dynmap.dynmapVersion must not be null
11.07 17:58:54 [Server] INFO at net.trivernis.chunkmaster.Chunkmaster.getDynmap(Chunkmaster.kt:109) ~[?:?]
11.07 17:58:54 [Server] INFO at net.trivernis.chunkmaster.Chunkmaster.onEnable(Chunkmaster.kt:39) ~[?:?]
11.07 17:58:54 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
11.07 17:58:54 [Server] INFO [Chunkmaster] Disabling Chunkmaster v1.2.1
11.07 17:58:54 [Server] INFO [Chunkmaster] Stopping all generation tasks...
11.07 17:58:54 [Server] ERROR Error occurred while disabling Chunkmaster v1.2.1 (Is it up to date?)
11.07 17:58:54 [Server] INFO kotlin.UninitializedPropertyAccessException: lateinit property generationManager has not been initialized
11.07 17:58:54 [Server] INFO at net.trivernis.chunkmaster.Chunkmaster.onDisable(Chunkmaster.kt:69) ~[?:?]
11.07 17:58:54 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
11.07 17:58:54 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

Looks like the issue is with Dynmap - the plugin won't start if it doesn't recognize the Dynmap version, or there's some kind of conflict. I've disabled Dynmap and it works fine.

**Comment by Trivernis** [comment]
Oh, my guess is that you're still using an old 1.15 dynmap version in 1.16.1. You should either update it or disable it.
