### ISSUE TITLE
Database Error: Error creating table generation_tasks

### ISSUE THREAD

**Issue by axipher** [Trivernis/spigot-chunkmaster#9]
I'm having a hard time getting ChunkMaster to work on PaperMC 1.14.4 Build #207

```
[09:31:47 INFO]: [Chunkmaster] Creating table generation_tasks with definition CREATE TABLE IF NOT EXISTS generation_tasks (id integer PRIMARY KEY AUTOINCREMENT,center_x integer NOT NULL DEFAULT 0,center_z integer NOT NULL DEFAULT 0,last_x integer NOT NULL DEFAULT 0,last_z integer NOT NULL DEFAULT 0,world text UNIQUE NOT NULL DEFAULT 'world',stop_after integer DEFAULT -1);
[09:31:50 ERROR]: [Chunkmaster] Error creating table generation_tasks.
```

I get the above error during server start-up and then any Chunkmaster commands afterwards cause Warnings as the database isn't set up.

The plugin is generating the files, but can't create the tables.

```
minecraft@COB:/mnt/minecraft/servers/AX_SV_002/plugins/Chunkmaster$ ls -al
total 4
drwxrwxrwx 2 root root   0 Sep 30 09:26 .
drwxrwxrwx 2 root root   0 Sep 30 09:17 ..
-rwxrwxrwx 1 root root   0 Sep 30 09:17 chunkmaster.db
-rwxrwxrwx 1 root root 172 Sep 30 09:26 config.yml
```

The server is running as a service through systemctl using the guide here: https://minecraft.gamepedia.com/Tutorials/Ubuntu_startup_script

**Comment by Trivernis** [comment]
@axipher Are there any other errors that appear in the log? What plugins are installed?
Does it work when you delete the `chunkmaster.db` file (so it gets recreated again on startup)?

**Comment by axipher** [comment]
No other errors, here is a pastebin of the log file: https://pastebin.com/UunuM35T

After the server has been up for a few minutes, I get this warning:

```
[09:54:25 WARN]: [Chunkmaster] Task #17 for Chunkmaster v0.12-beta generated an exception
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: generation_tasks)
        at org.sqlite.core.DB.newSQLException(DB.java:941) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.core.DB.newSQLException(DB.java:953) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.core.DB.throwex(DB.java:918) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:134) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.core.DB.prepare(DB.java:257) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[patched_1.14.4.jar:git-Paper-207
]
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[patched_1.14.4.jar:git-Paper-207
]
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[patched_1.14.4.jar:git-Paper-207]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[patched_1.14.4.jar:git-Paper-207]
        at net.trivernis.chunkmaster.lib.generation.GenerationManager.startAll(GenerationManager.kt:176) ~[?:?]
        at net.trivernis.chunkmaster.lib.generation.GenerationManager$init$2.run(GenerationManager.kt:150) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-207]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1
.14.4.jar:git-Paper-207]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-207]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-207]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-207]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-207]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

Plugins:
- chunkmaster.jar
- Dynmap-3.0-beta-5-spigot.jar
- EssentialsX-2.17.1.0.jar
- GriefPrevention.jar
- worldedit-bukkit-7.0.1.jar



I tried deleting the database file and restarting the server and same Error happened where it couldn't create the table.

```
[09:59:01 INFO]: [Chunkmaster] Enabling Chunkmaster v0.12-beta
[09:59:01 INFO]: [Chunkmaster] Initializing Database...
[09:59:01 INFO]: [Chunkmaster] Database connection established.
[09:59:01 INFO]: [Chunkmaster] Creating table generation_tasks with definition CREATE TABLE IF NOT EXISTS generation_tasks (id integer PRIMARY KEY AUTOINCREMENT,center_x integer NOT NULL DEFAULT 0,center_z integer NOT NULL DEFAULT 0,last_x integer NOT NULL DEFAULT 0,last_z integer NOT NULL DEFAULT 0,world text UNIQUE NOT NULL DEFAULT 'world',stop_after integer DEFAULT -1);
[09:59:04 ERROR]: [Chunkmaster] Error creating table generation_tasks.
[09:59:04 INFO]: [Chunkmaster] Database fully initialized.
[09:59:04 INFO]: [Chunkmaster] Creating task to load chunk generation Tasks later...
```

**Comment by Trivernis** [comment]
Can you test it with the [latest build](https://21-208644898-gh.circle-artifacts.com/0/build/chunkmaster-0.12-beta.jar) and tell me what the error is?

**Comment by axipher** [comment]
Here is the log: https://pastebin.com/xpSY4v0r

```
[07:43:30] [Server thread/INFO]: [Chunkmaster] Enabling Chunkmaster v0.12-beta
[07:43:30] [Server thread/INFO]: [Chunkmaster] Initializing Database...
[07:43:30] [Server thread/INFO]: [Chunkmaster] Database connection established.
[07:43:30] [Server thread/INFO]: [Chunkmaster] Creating table generation_tasks with definition CREATE TABLE IF NOT EXISTS generation_tasks (id integer PRIMARY KEY AUTOINCREMENT,center_x integer NOT NULL DEFAULT 0,center_z integer NOT NULL DEFAULT 0,last_x integer NOT NULL DEFAULT 0,last_z integer NOT NULL DEFAULT 0,world text UNIQUE NOT NULL DEFAULT 'world',stop_after integer DEFAULT -1);
[07:43:33] [Server thread/ERROR]: [Chunkmaster] Error creating table generation_tasks.
[07:43:33] [Server thread/ERROR]: [Chunkmaster] [SQLITE_BUSY]  The database file is locked (database is locked)
[07:43:33] [Server thread/INFO]: [Chunkmaster] [Ljava.lang.StackTraceElement;@ee303eb
[07:43:33] [Server thread/INFO]: [Chunkmaster] Database fully initialized.
[07:43:33] [Server thread/INFO]: [Chunkmaster] Creating task to load chunk generation Tasks later...
```

Then after a couple minutes of uptime:
```
[07:44:03] [Server thread/WARN]: [Chunkmaster] Task #12 for Chunkmaster v0.12-beta generated an exception
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: generation_tasks)
    at org.sqlite.core.DB.newSQLException(DB.java:941) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.core.DB.newSQLException(DB.java:953) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.core.DB.throwex(DB.java:918) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.core.NativeDB.prepare(NativeDB.java:134) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.core.DB.prepare(DB.java:257) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[patched_1.14.4.jar:git-Paper-207]
    at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[patched_1.14.4.jar:git-Paper-207]
    at net.trivernis.chunkmaster.lib.generation.GenerationManager.startAll(GenerationManager.kt:176) ~[?:?]
    at net.trivernis.chunkmaster.lib.generation.GenerationManager$init$2.run(GenerationManager.kt:150) ~[?:?]
    at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-207]
    at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-207]
    at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-207]
    at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-207]
    at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-207]
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-207]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by Trivernis** [comment]
So the database file is locket which is probably because one statement wasn't closed. I think I fixed it but because the error never occured for me I can't test it. Can you test with [this build](https://22-208644898-gh.circle-artifacts.com/0/build/chunkmaster-0.13-beta.jar) if the error still occurs? If it does occur can you check if other processes are using the database file (for whatever reason) by using `fuser` or something similar?

**Comment by axipher** [comment]
Tried the new build, made sure to delete the ChunkMaster folder, still get the following error:
```
[08:14:47 ERROR]: [Chunkmaster] Error creating table generation_tasks.
[08:14:47 ERROR]: [Chunkmaster] [SQLITE_BUSY]  The database file is locked (database is locked)
[08:14:47 INFO]: [Chunkmaster] org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.execute(DB.java:854)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:56)
        at net.trivernis.chunkmaster.lib.SqlUpdateManager.performUpdate(SqlUpdateManager.kt:63)
        at net.trivernis.chunkmaster.Chunkmaster.initDatabase(Chunkmaster.kt:85)
        at net.trivernis.chunkmaster.Chunkmaster.onEnable(Chunkmaster.kt:31)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
        at java.lang.Thread.run(Thread.java:748)
```

I ran `fuser` and the only thing that is using `chunkmaster.db` is the PID for the java process running minecraft.



My quick googling just kept going back to saying this can typically happen if you have more than one connection open to the database by forgetting to close a connection.  I haven't peeked at your code or anything yet, but could it be that a second connection is getting created at some point before another one has had enough time to close?

**Comment by Trivernis** [comment]
I've rewritten the whole database management stuff and ensured that every statement gets closed. I also switched to establishing a connection only when performing database operations and closing it afterwards.
You can test [this build](https://23-208644898-gh.circle-artifacts.com/0/build/chunkmaster-0.13-beta.jar), if that doesn't work I'm out of ideas.

**Comment by axipher** [comment]
So it's still not working on my Linux box, see below for errors and troubleshooting.  I did decide to grab a copy of the server and copy it to my Windows Laptop and it runs perfectly fine on there, no issues and chunkmaster.db becomes a non-zero size with no errors.



On the Linux side, I decided to try `lsof chunkmaster.db` and it looks like when the Error during table generation happens, it jumps to two connections immediately, and each subsequent "generate" command starts a new connection never closing off the older ones.  So it's something to do with how the connections are being handled on Linux for some reason.


```
minecraft@COB:/mnt/minecraft/servers/AX_SV_002/plugins/Chunkmaster$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

I even tried updating sqlite3 to a newer version then the 3.11 that Ubuntu 16.04 was stuck on and still getting the database locked error.
```
minecraft@COB:/mnt/minecraft/servers/AX_SV_002/plugins/Chunkmaster$ sqlite3 --version
3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f
minecraft@COB:/mnt/minecraft/servers/AX_SV_002/plugins/Chunkmaster$ sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
```

This is the LSOF output after running a few generate commands in a row, each of them failing do to the table missing in the database:
```
Every 2.0s: lsof chunkmaster.db                                                                              Wed Oct  2 11:17:38 2019

COMMAND   PID      USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
java    23633 minecraft   68u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   69u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   71u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   72u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   73u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   74u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   75u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   76u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   77u   REG   0,42        0 4409943 chunkmaster.db
java    23633 minecraft   78u   REG   0,42        0 4409943 chunkmaster.db
```

**Comment by Trivernis** [comment]
Okay, thanks for all the information. I guess it is a problem with the sqlite jdbc driver then. Maybe it is not supported on Ubuntu 16, it is working on my Ubuntu Server 18 machine.

I'm going to test if it is an issue with the ubuntu version.

**Comment by axipher** [comment]
Sounds good, let me know if you need any additional help or testing.

I can give it a quick try on my Ubuntu 19.04 PC tonight.

If you have it working on 18 though, I may also look at upgrading the VM that is currently at 16.04 to 18.04 as a early solution if I get a chance to.

**Comment by Trivernis** [comment]
I've tested it on ubuntu 16.4.6 with paper #207 without problems

Edit: At least the problem with multiple connections being established on error should be fixed.

**Comment by axipher** [comment]
I finally had some time to sit down and start trying to replicate the issue, turns out its something that is so simple that it hurts, but the errors messages are not clear from SQLite at all.

I completely forgot that my Servers were being stored on share on my Host System (Unraid) and the VM (Ubuntu 16.04.6) was mounting that share with full permissions as a `cifs` share.  So SQLite could create the file no problem, but something about SQLite does not play nicely with `.db` files on a mounted network share.

I simply moved the entire server directory to the `home` directory of the `minecraft` user, started it up, and everything worked fine, `chunkmaster.db` was filling up as a non-zero file and no Errors on the minecraft server.

Now I just need to figure out a way to get this to work while storing the world data and dynmap tiles on the mounted share and backup everything correctly periodically.

Sorry for this wild goose chase at this point.

I'm not sure if there is anything that can be done to fix the issue with SQLite databases on mounted shares by your code, so you can Close this Issue if you don't have anything else to add.

**Comment by Trivernis** [comment]
Well, at last we've got that figured out. I added a config parameter to change the name of the database file (including extension) in [the latest build](https://25-208644898-gh.circle-artifacts.com/0/build/chunkmaster-0.13-beta.jar).

**Comment by axipher** [comment]
So I tried it with a custom path and it looks like it gets forced to a relative path so its adding my full path I defined to the Chunkmaster folder:

I changed `config.yml` as follows:
```
database:
  filename: /home/minecraft/AX_SV_002_chunkmaster.db
```

And get this error:
```
[15:14:11 INFO]: [Chunkmaster] Enabling Chunkmaster v0.13-beta
[15:14:11 INFO]: [Chunkmaster] Initializing Database...
[15:14:11 ERROR]: [Chunkmaster] Could not get database connection.
[15:14:11 ERROR]: [Chunkmaster] path to '/mnt/minecraft/servers/AX_SV_002/plugins/Chunkmaster//home/minecraft/AX_SV_002_chunkmaster.db': '/mnt/minecraft/servers/AX_SV_002/plugins/Chunkmaster/home' does not exist
[15:14:11 WARN]: [Chunkmaster] Failed to init database: null
[15:14:11 INFO]: [Chunkmaster] Creating task to load chunk generation Tasks later...
```



Now I can get around the Error by editing the `config.yml` file as follows and adding a bunch of `../` to get back to the root file system then back through the home directory and this works perfectly fine.
```
database:
  filename: ../../../../../../home/minecraft/AX_SV_002_chunkmaster.db
```


So with your latest build, there is a solution and I can run the server from a mounted network share as long as I place the `chunkmaster.db` file somewhere on the local disk of the Linux OS and use

**Comment by Trivernis** [comment]
Yes, the path is always relative to the folder of the plugin

**Comment by axipher** [comment]
Well thanks for adding the configuration option to the plugin at least, will test this later tonight when I have time to actually login to the server as a player and see it in action.
