### ISSUE TITLE
[BUG] setCenter throws error when given a world name as a player

### ISSUE THREAD

**Issue by Rytexs** [Trivernis/spigot-chunkmaster#94]
[23:16:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chunkmaster' in plugin Chunkmaster v1.3.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-134]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$5244/0000000000000000.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$3050/0000000000000000.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.util.Arrays$ArrayList.get(Arrays.java:4195) ~[?:?]
        at net.trivernis.chunkmaster.commands.CmdSetCenter.validateThreeArgs(CmdSetCenter.kt:82) ~[?:?]
        at net.trivernis.chunkmaster.commands.CmdSetCenter.execute(CmdSetCenter.kt:49) ~[?:?]
        at net.trivernis.chunkmaster.commands.CommandChunkmaster.onCommand(CommandChunkmaster.kt:43) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-134]
        ... 20 more

**Comment by Trivernis** [comment]
@Rytexs could you please be a bit more descriptive with your bug report and maybe have a look at the bug report [issue template)(https://github.com/Trivernis/spigot-chunkmaster/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

For instance what did you do to produce this error message?

**Comment by Rytexs** [comment]
I wrote / chunkmaster setCenter Survival then the error came

**Comment by Trivernis** [comment]
Did you do it as a player?

**Comment by Rytexs** [comment]
No i have OP

**Comment by Trivernis** [comment]
No, did you execute the command as a player in the chat or in the server console?

**Comment by Rytexs** [comment]
as a player

**Comment by Trivernis** [comment]
Ok
I'll look into it

**Comment by Rytexs** [comment]
Hay 1 more
I have chunkmaster on and the dynmap loading not....
Why ?

**Comment by Trivernis** [comment]
Because dynmap is slower than chunkmaster. Just wait longer
